name: PlexNFOCreator
options:
  bundleIdPrefix: com.roto31
  deploymentTarget:
    macOS: "14.0"
packages:
  PlexNFOCreatorPackage:
    path: .
targets:
  PlexNFOCreator:
    type: application
    platform: macOS
    sources:
      - PlexNFOCreator/Sources/PlexNFOCreator
    dependencies:
      - package: PlexNFOCreatorPackage
        product: PlexNFOCore
    settings:
      base:
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        PRODUCT_BUNDLE_IDENTIFIER: com.roto31.PlexNFOCreator
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: YES
